# Generated by Django 4.2.30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ai.request", "AI Request"),
                            ("ai.request.success", "AI Request Success"),
                            ("ai.request.error", "AI Request Error"),
                            ("ai.tool.call", "AI Tool Call"),
                            ("ai.tool.error", "AI Tool Error"),
                            ("ai.tool.blocked", "AI Tool Blocked"),
                            ("ai.tool.rejected", "AI Tool Rejected"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("standard", "Standard"), ("mcp", "MCP")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "adapter",
                    models.CharField(
                        blank=True,
                        choices=[("none", "None"), ("mock", "Mock"), ("stdio", "Stdio")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("tool_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "tool_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("blocked", "Blocked"),
                            ("error", "Error"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("readonly", models.BooleanField(default=True)),
                ("permission_filtered", models.BooleanField(blank=True, null=True)),
                ("raw_result_returned", models.BooleanField(default=False)),
                ("write_operation", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("item_count", models.PositiveIntegerField(blank=True, null=True)),
                ("prompt_length", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("source", models.CharField(default="pi-chat", max_length=32)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_audit_events",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Audit Event",
                "verbose_name_plural": "AI Audit Events",
                "db_table": "ai_audit_events",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="idx_ai_audit_ws_created",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="idx_ai_audit_actor_created",
                    ),
                    models.Index(
                        fields=["event", "created_at"],
                        name="idx_ai_audit_event_created",
                    ),
                ],
            },
        ),
    ]
